version: '3'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
 
    volumes:
      - mongodb_data:/data/db
 
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
 
  django_app:
    build:
      context: .
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: 'mongodb://admin:password@mongodb:27017/'

  java_dependency:
    image: openjdk:latest  # Use the latest OpenJDK image
    command: tail -f /dev/null  # Keep the container running, since you don't have a Java application
    depends_on:
      - mongodb
 
volumes:
  mongodb_data:
